/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:eb7cecf5-2f77-4da0-804d-07db925e622e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kHR7RdDTm",
    "aws_user_pools_web_client_id": "7b7icko0n0g8i22v8nfd0pftn2",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "us-east-1",
            "maps": {
                "items": {
                    "alsDemoApp-dev": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "alsDemoApp-dev"
            },
            "geofenceCollections": {
                "items": [
                    "alsDemoAppCollection-dev"
                ],
                "default": "alsDemoAppCollection-dev"
            }
        }
    }
};


export default awsmobile;
